CREATE TABLE tb_users (
  id SERIAL PRIMARY KEY,
  first_name VARCHAR(50) NOT NULL,
  last_name VARCHAR(255) NOT NULL,
  cpf VARCHAR(11) UNIQUE NOT NULL,
  email VARCHAR(50) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL,
  balance NUMERIC(12, 2) NOT NULL,
  user_type VARCHAR(30) NOT NULL DEFAULT 'REGULAR'
);


CREATE TABLE tb_transactions (
  id SERIAL PRIMARY KEY,
  amount NUMERIC(12, 2) NOT NULL,
  sender VARCHAR(50) NOT NULL,
  receiver VARCHAR(50) NOT NULL,
  timestamp TIMESTAMP WITHOUT TIME ZONE,
  CONSTRAINT fkey_transactions_users FOREIGN KEY(id) REFERENCES tb_users(id)
);